/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus;

import static com.google.common.base.Objects.equal;

public class HelloOtus {
    public static void main(String... args) {
        String sourceString = "Hello Otus";
        System.out.println(equal(sourceString, "Hello otus"));
    }
}
